### ISSUE TITLE
ETHUSDT

### ISSUE THREAD

**Issue by sprototles** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#15]
when buying ETH
Traceback (most recent call last):
  File "D:\Downloads\Schneider\ScriptingPath\Crypto\Binance-News-Sentiment-Bot-main\news-analysis.py", line 447, in <module>
    buy(compiled_sentiment, headlines_analysed)
  File "D:\Downloads\Schneider\ScriptingPath\Crypto\Binance-News-Sentiment-Bot-main\news-analysis.py", line 348, in buy
    test_order = client.create_test_order(symbol=coin+PAIRING, side='BUY', type='MARKET', quantity=volume[coin+PAIRING])
  File "D:\Program_files\Python\Python39\lib\site-packages\binance\client.py", line 1633, in create_test_order
    return self._post('order/test', True, data=params)
  File "D:\Program_files\Python\Python39\lib\site-packages\binance\client.py", line 295, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "D:\Program_files\Python\Python39\lib\site-packages\binance\client.py", line 242, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "D:\Program_files\Python\Python39\lib\site-packages\binance\client.py", line 237, in _request
    return self._handle_response()
  File "D:\Program_files\Python\Python39\lib\site-packages\binance\client.py", line 285, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: LOT_SIZE

**Comment by CyberPunkMetalHead** [comment]
Thanks, this should now be resolved in the last commit.
